### PR TITLE
ASCII and CMake Support

### PR DESCRIPTION
**Pull request by DeveloperPaul123**
I've added the following features:
- Support for openning of properly formed ASCII .stl files (I'll more than likely improve this a bit more)
- Support for configuring the project using CMake. Good way to separate source and build, that way people can use whatever compiler works for them. 
- Added comments where I could, this is a WIP.

### CODE REVIEW

**Comment by mkeeter** [comment]
I've ended up implementing ASCII STLs in the course of miscellaneous updates, so I'm going to close this for now – it's trying to do a lot of things simultaneously (ASCII STLs / cmake support / Windows DLLs? / Doxygen-style comments?), which makes me nervous.

**Comment by DeveloperPaul123** [comment]
@mkeeter Are you open to adding cmake support and/or doxygen style comments? If so I can clean up what I did and PR again. 

Let me know.

**Comment by mkeeter** [comment]
I'd be open to switching from `qmake` to `cmake` – if you submit that as a standalone PR, I'll merge it in.

I'm not interested in Doxygen comments, because the whole program is meant to be small / understandable – if it gets to the point where people need to run an external documentation-generating tool to learn about the code, then it has have grown too large!

**Comment by DeveloperPaul123** [comment]
@mkeeter Sounds good.

**Pull request closed without merging**
