### PR TITLE
folder navigation

### PR DESCRIPTION
**Pull request by phreaker0**
This PR adds the ability to switch between stl files in the current loaded file folder by using the left and right arrow key.

### CODE REVIEW

**Comment by mkeeter** [comment]
Looks good to me, and works fine on Mac.  What OS did you test this on, just for completeness?

**Comment by phreaker0** [comment]
@mkeeter Linux:
```
$ lsb_release -a
LSB Version:	core-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```

**Comment by mkeeter** [comment]
Cool, looks good.

Out of curiosity, how many STLs did you need in a folder before the insertion-style list-construction was a noticeable speedup?

**Comment by phreaker0** [comment]
I didn't test it out before but it bothered me that it was not as fast as it could be :-) As your title says "fastest stl viewer", so this should also be true for the navigation part. I just did a quick and dirty speed test with 10000 stl files in the folder:
sort list after it was built: 111 057 796 ns
_____ ____sorted insert: 59 608 720 ns

**Pull request merged**
